{% set version = "0.4.21" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mhsmm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mhsmm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mhsmm/mhsmm_{{ version }}.tar.gz
  sha256: 293544afb194934b1d58cf88c6f8c372f537745514b6e428cf83ae62e87d2bba

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mvtnorm
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mvtnorm

test:
  commands:
    - $R -e "library('mhsmm')"           # [not win]
    - "\"%R%\" -e \"library('mhsmm')\""  # [win]

about:
  home: https://github.com/jaredo/mhsmm
  license: GPL-2.0-or-later
  summary: |
    Parameter estimation and prediction for hidden Markov and semi-Markov models for data
    with multiple observation sequences.  Suitable for equidistant time series data,
    with multivariate and/or missing data. Allows user defined emission distributions.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
