travis:
  secure:
    BINSTAR_TOKEN: N5Z+lS7HLDWy3sXuGJmVYyB2F/tROtNZqGWdP5fvdA9rhs0pMo9oJt9+sFpoZRgzikixfg7HMQn88kvrpUkR7uQTFCT++IFQSterW4UhApMoHdekK7uu+ok0pKvoHM/347v8N1Po+Gt4RjTsfJFxO/SLuoFmn5G7LjqB5duNYzCW4L8y993Q5i2uo7CiN5JIiNhk8pvxZWpd1Rj37iFUpDGAqo27Z6E7eJ7V2ILc+0lpZpG1giykDpQRq+1hoq6K/zljlUoNwcPnUlJjF4JsdIxE3ehT5RK7kRg9ce+ksONiRM6llpCnVNiPSzPn44arvka4Cipat4VkS2i+2GHUUlRNKcg/vAO2GMyGTf1NRwPm73munfI0Jrcx02pVCGAEb05q45aQQ5qLXK8BhINFXfWZznrh28kuY9QsKNKT25weRAgSpDHGK66VrUIXCgWswXOGRskJotiSzwsmOW7trdOg5vzgUHiF7WaBynLg2bBYpugDgPj5GSkKI5DVp8YN7e9WL7e8pvMJ0sh8s6gMUnLYBkGlnIjR4uFN26R+0qsf+cDrSFhfhpM1G2YkmeYn0/tPCtHbwOTphSrnyRdVIo+alaZpMf3vs0DGziBIUxfSqMi+sSPU+BvyW5gn2bXUBxtRsiOS9RlNSRcu/GVeySVAsx2jC+wXoL8UaNWsop8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
