travis:
  secure:
    BINSTAR_TOKEN: g9tgdjEY80WNhb7nXhGA3VxmdT591OmZ2ZMBWDp9Y6hf/42zgcAK2VJ56x8YGCxBYpfJyRfTnXdoWXsJbU9AyOpIGB2s/4HCELaOKDsWownHsjlBinuxy7Vz7YgHXRCS3KfJioS3eS2VUXZyiduNE4S+DgXsAjQzLM4h7FQg+iCWOogD/UXGCTYpAjvasiKFzRA0mmEYOrib+5jsfweC5p5qmzw1IKGicd6mp3+fAhAIPi+vJZq2NmcmjLg2zAMB3xZ1U6C4y54L2zENj3oJqKVRxuDrOp6iC8Pj3yjx1LIvHDllY9gIZ1Rdxd9mIwOtljss0o3RDsjT7XT/YgJCK8YmXj/j7Sjphxfq/VS6re4B3/CpGwMLHCbu9iRfKZy4c2fUDap8InP7GCF7i6BsVgFV5LsYylaY10Ih1iGRxLs5/fIQNOXuxhleGVmJi74lSDIni8+3IC1KKmecWxAlczmIaIp3Wpk6pQ59xj8kMhHOYgQXR3DBWNmbYxZxX+YRFyUrmItxElonP0PAa/4Qs5JViORT7Hp6qCotl8muPerfXUnVyOXm17IhoMx1Sgxw5EhqPE0Ne2gdU9J0cBMzo/xe4laWHPNLtRoAWyL/6tkNgBovqrLCSeZdoUiKU6H2y11+rfvHAYOVCia1RfI3se975ROXUXxano9MnooihWU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
